name: Build and Push Docker Image

on:
  workflow_dispatch:  # Allows manual triggering from the GitHub UI
  push:
    branches:
      - main  # Trigger on push to main branch (you can change this to any branch you prefer)

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Install jq
      run: sudo apt-get update && sudo apt-get install -y jq
  
    - name: Build, Push Docker Images and Set Dockerfile URL
      run: |
        echo "Building, pushing Docker images and setting Dockerfile URL..."
        dockerfiles=$(find . -name '*.Dockerfile')
        for dockerfile in $dockerfiles; do
          image_name="docker.io/cyberdog123/$(basename ${dockerfile%.*}):latest"
          echo "image name: $image_name"
          echo "dockerfile path: $dockerfile"
          docker build -f $dockerfile -t $image_name .
          docker push $image_name
          repo_name=$(basename ${dockerfile%.*})
          dockerfile_url="https://github.com/${{ github.repository }}/blob/main/$dockerfile"
          curl -X PATCH \
          -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
          -H "Accept: application/vnd.github.v3+json" \
          https://api.github.com/repos/${{ github.repository }}/docker/${repo_name} \
          -d "{\"description\":\"Dockerfile URL: $dockerfile_url\"}"
        done
